### ISSUE TITLE
Lua Grammar Inaccuracies

### ISSUE THREAD

**Issue by GiffE** [eatonphil/lust#1]
Hey,

Loved the article but I when going through saw a few things that are inaccurate to the Lua grammar.  I understand the intent is to teach a _subset_ of Lua, not a production ready environment.  Not to be pedantic about it, but this is more of a _dialect_ of Lua than a _subset_.  

In the article you state:
>The boring part is defining the tree. Generally speaking (and specifically for this project), the syntax tree is a list of statements. **Statements can be function definitions or expression statements** or if statements or return statements or local declarations.

While this is true for most languages, it's actually incorrect for Lua.  Lua's grammar uniquely disallows expressions as statements with one exception, function calls.
This is [important in resolving ambiguity](https://www.seventeencups.net/posts/how-lua-avoids-semicolons/) that looks like this:
```lua
local x = 1 -- Does the statement end here?
- 1         -- Or does it end here?
```

The next difference is:
>Return statements just check for the return keyword, an expression, **and a semicolon.**

Lua optionally allows semicolon statement terminators.  They are not required.  This introduces ambiguity in situations like this:
```lua
function foo()
    return
    bar()
end
```
Parsing this can either mean "return nothing and call bar" or "return the result of call to bar"
Lua's rules solves this ambiguity by _forcing return to always be the last statement in the block_.
 
Lua is a rather unique whitespace agnostic language.  These 2 rules are pivotal to that, so I was hoping to see how you implemented Lua's grammar. Again none of this is to criticize your article or implementation, I quite enjoyed it as a fan of rust, Lua and language design at large.

**Comment by eatonphil** [comment]
Great critique, thank you! To be honest this is like the third time I've written any Lua code so I definitely don't know the language well. I don't think I'll change anything since a perfect Lua subset wasn't really the goal. But I'll add a note to the blog linking to this.

**Comment by GiffE** [comment]
Yeah, I wouldn't change anything either.  The way you have it is excellent for the intent of the work.
